CREATE TABLE controle_calibracao (
    cal_id INT(10) AUTO_INCREMENT,
    cal_codigo_sgi VARCHAR(20),
    cal_num_patrimonio VARCHAR(20),
    cal_codigo_sap INT(10),
    cal_propriedade INT(10),
    cal_marca VARCHAR(50),
    cal_modelo VARCHAR(50),
    cal_serial_number VARCHAR(50),
    cal_descricao VARCHAR(100),
    cal_local_uso VARCHAR(50),
    cal_data_certificado_calibracao_avaliacao DATE,
    cal_data_validade_certificado_calibracao_avaliacao DATE,
    cal_freq_calibracao INT(4),
    cal_situacao_equipamento VARCHAR(50),
    cal_tipo_calibracao CHAR(1),
    cal_criterio_aceitacao VARCHAR(50),
    cal_laboratorio_calibracao VARCHAR(50),
    cal_data_validade_garantia DATE,
    cal_equip_necessitou_reparo BOOLEAN,
    cal_data_reparo DATE,
    cal_observacao TINYTEXT,
    PRIMARY KEY (cal_id),
    FOREIGN KEY (cal_propriedade) REFERENCES clientes(cli_id)
)